import { isSlackApiEndpoint } from './slack-endpoint';

/**
 * The deployment variable holding the secret the Socket Mode bridge (`slack-socket/`, RM7)
 * presents to the backend's internal HTTP routes. Generated by the setup verb, written to the
 * deployment and to the bridge's environment alike; absent where no bridge runs, and then no
 * request carries buttons.
 */
export const SOCKET_BRIDGE_SECRET_VAR = 'DAY0_SOCKET_BRIDGE_SECRET';

/** Why an employee's decision requests carry the typed code alone, without buttons. */
export type ButtonsUnavailable =
  /** The card is not Slack's documented Web API (an MCP chat tool sends text alone). */
  | 'not-slack-api'
  /** The card connects through a token that is not an app Day0 created for the employee. */
  | 'no-own-app'
  /** The employee's app has no app-level token yet (a person generates it, K2). */
  | 'no-app-level-token'
  /** The deployment runs no Socket Mode bridge to carry a press. */
  | 'no-bridge';

/** Whether an employee's decision requests carry Approve and Reject buttons, and why not. */
export type DecisionButtons =
  | { readonly available: true }
  | { readonly available: false; readonly why: ButtonsUnavailable };

/** The fields of a chat card the buttons depend on. */
export interface ButtonsCard {
  readonly path?: string;
  readonly endpoint?: string;
  readonly provisioning?: { readonly appLevelTokenCredentialId?: unknown };
}

/**
 * Whether a chat card's decision requests carry buttons (wave 12, 12-M; RM3 (a)): only on Slack's
 * documented Web API, through the employee's own app, once its app-level token has landed, on a
 * deployment whose Socket Mode bridge is configured. Otherwise the typed code alone, which always
 * decides, and the reason the card shows.
 *
 * @param card - The chat card the requests go through.
 * @param bridgeConfigured - Whether the deployment holds the bridge's secret.
 */
export function decisionButtonsFor(card: ButtonsCard, bridgeConfigured: boolean): DecisionButtons {
  if (card.path !== 'documented-api' || !isSlackApiEndpoint(card.endpoint)) {
    return { available: false, why: 'not-slack-api' };
  }
  if (card.provisioning === undefined) return { available: false, why: 'no-own-app' };
  if (card.provisioning.appLevelTokenCredentialId === undefined) {
    return { available: false, why: 'no-app-level-token' };
  }
  if (!bridgeConfigured) return { available: false, why: 'no-bridge' };
  return { available: true };
}

/**
 * Whether this deployment's environment holds the bridge's secret.
 *
 * @param env - The environment to read; the process's own by default.
 */
export function socketBridgeConfigured(
  env: Readonly<Record<string, string | undefined>> = process.env,
): boolean {
  return (env[SOCKET_BRIDGE_SECRET_VAR] ?? '').trim() !== '';
}
