import { isSlackApiEndpoint } from './slack-endpoint';

/**
 * The deployment variable holding the secret the Socket Mode bridge (`slack-socket/`, RM7)
 * presents to the backend's internal HTTP routes. Generated by the setup verb, written to the
 * deployment and to the bridge's environment alike; absent where no bridge runs, and then no
 * request carries buttons.
 */
export const SOCKET_BRIDGE_SECRET_VAR = 'DAY0_SOCKET_BRIDGE_SECRET';

/** Why an employee's decision requests carry no Approve and Reject buttons. */
export type ButtonsUnavailable =
  /** The card is not Slack's documented Web API (an MCP chat tool sends text alone). */
  | 'not-slack-api'
  /** The card connects through a token that is not an app Day0 created for the employee. */
  | 'no-own-app'
  /** The employee's app has no app-level token yet (a person generates it, K2). */
  | 'no-app-level-token'
  /** The deployment runs no Socket Mode bridge to carry a press. */
  | 'no-bridge';

/** Whether an employee's decision requests carry Approve and Reject buttons, and why not. */
export type DecisionButtons =
  | { readonly available: true }
  | { readonly available: false; readonly why: Exclude<ButtonsUnavailable, 'no-bridge'> }
  | {
      readonly available: false;
      readonly why: 'no-bridge';
      /** Whether the app's app-level token is stored, so the bridge is all that is missing. */
      readonly tokenStored: boolean;
    };

/** The fields of a chat card the buttons depend on. */
export interface ButtonsCard {
  readonly path?: string;
  readonly endpoint?: string;
  readonly provisioning?: { readonly appLevelTokenCredentialId?: unknown };
}

/**
 * Whether a chat card's decision requests carry buttons (wave 12, 12-M; RM3 (a)): only on Slack's
 * documented Web API, through the employee's own app, on a deployment whose Socket Mode bridge is
 * configured, once the app's app-level token has landed. The bridge is read before the token, so a
 * card on a deployment that runs none asks for no token it could not use (W12-R18). Otherwise the
 * reason the card shows; the typed code still decides where the app takes messages (W12V-7).
 *
 * @param card - The chat card the requests go through.
 * @param bridgeConfigured - Whether the deployment holds the bridge's secret.
 */
export function decisionButtonsFor(card: ButtonsCard, bridgeConfigured: boolean): DecisionButtons {
  if (card.path !== 'documented-api' || !isSlackApiEndpoint(card.endpoint)) {
    return { available: false, why: 'not-slack-api' };
  }
  if (card.provisioning === undefined) return { available: false, why: 'no-own-app' };
  const tokenStored = card.provisioning.appLevelTokenCredentialId !== undefined;
  if (!bridgeConfigured) return { available: false, why: 'no-bridge', tokenStored };
  if (!tokenStored) return { available: false, why: 'no-app-level-token' };
  return { available: true };
}

/**
 * Whether this deployment's environment holds the bridge's secret.
 *
 * @param env - The environment to read; the process's own by default.
 */
export function socketBridgeConfigured(
  env: Readonly<Record<string, string | undefined>> = process.env,
): boolean {
  return (env[SOCKET_BRIDGE_SECRET_VAR] ?? '').trim() !== '';
}

/** One button press, as the bridge forwards it from a Socket Mode `block_actions` envelope. */
export interface SocketPress {
  /** The Slack user who pressed. */
  readonly userId: string;
  readonly teamId?: string;
  /** The app whose message carried the button. */
  readonly appId: string;
  readonly channelId: string;
  /** The message the button is on. */
  readonly messageTs: string;
  /** When the press happened, Slack's own timestamp: the press's key, so a redelivery is one press. */
  readonly actionTs: string;
  readonly action: { readonly action_id: string; readonly value?: string };
}

function record(value: unknown): Record<string, unknown> | undefined {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : undefined;
}

function text(value: unknown): string | undefined {
  return typeof value === 'string' && value.trim() !== '' ? value : undefined;
}

/**
 * Read a Socket Mode envelope's payload as one button press, or nothing: only a `block_actions`
 * payload naming the user, the app, the message, its channel and an action with its timestamp.
 *
 * @param payload - The envelope's `payload`, as Slack sent it.
 */
export function parsePress(payload: unknown): SocketPress | undefined {
  const body = record(payload);
  if (body?.type !== 'block_actions') return undefined;
  const container = record(body.container);
  const first = Array.isArray(body.actions) ? record(body.actions[0]) : undefined;
  const userId = text(record(body.user)?.id);
  const appId = text(body.api_app_id);
  const channelId = text(container?.channel_id) ?? text(record(body.channel)?.id);
  const messageTs = text(container?.message_ts);
  const actionId = text(first?.action_id);
  const actionTs = text(first?.action_ts);
  if (!userId || !appId || !channelId || !messageTs || !actionId || !actionTs) return undefined;
  const teamId = text(record(body.team)?.id);
  const value = text(first?.value);
  return {
    userId,
    ...(teamId === undefined ? {} : { teamId }),
    appId,
    channelId,
    messageTs,
    actionTs,
    action: { action_id: actionId, ...(value === undefined ? {} : { value }) },
  };
}

async function digest(value: string): Promise<Uint8Array> {
  return new Uint8Array(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value)));
}

/**
 * Whether an `Authorization` header presents the bridge's secret as a bearer token. Both sides are
 * hashed before they are compared byte for byte without an early exit, so the time taken says
 * nothing about how much of the secret a guess got right. An empty secret matches nothing.
 *
 * @param header - The request's `Authorization` header, if any.
 * @param secret - The deployment's {@link SOCKET_BRIDGE_SECRET_VAR}.
 */
export async function bridgeSecretMatches(header: string | null, secret: string): Promise<boolean> {
  if (secret === '' || header === null || !header.startsWith('Bearer ')) return false;
  const [presented, expected] = await Promise.all([
    digest(header.slice('Bearer '.length)),
    digest(secret),
  ]);
  let difference = 0;
  for (let index = 0; index < expected.length; index += 1) {
    difference |= (presented[index] ?? 0) ^ (expected[index] ?? 0);
  }
  return difference === 0;
}

/** An app-level token's shape: Slack's `xapp-` prefix and its token characters. */
const APP_LEVEL_TOKEN = /^xapp-[A-Za-z0-9_-]{8,}$/;

/** Whether a pasted value has an app-level token's shape. */
export function isAppLevelTokenShape(value: string): boolean {
  return APP_LEVEL_TOKEN.test(value);
}

/** Why a pasted value was refused before Slack was asked: it is not an app-level token. */
export const NOT_AN_APP_LEVEL_TOKEN =
  "That is not an app-level token: Slack's app-level tokens start with xapp-. Generate one in the app's settings under Basic Information, App-Level Tokens, with the connections:write scope.";

/** Why a card takes no app-level token: it connects through no app of the employee's own. */
export const NO_OWN_APP_FOR_TOKEN =
  "This card has no Slack app of the employee's own, so it takes no app-level token. Create the employee's own Slack app on this card first; until then the request's typed code decides.";

/**
 * Why Slack refused an app-level token when Day0 opened a connection with it.
 *
 * @param appName - The employee's app, as the card names it.
 * @param reason - Slack's refusal, the token already removed.
 */
export function appLevelTokenRefused(appName: string, reason: string): string {
  return `Slack did not accept this app-level token (${reason}). Check that it was generated for ${appName} with the connections:write scope, and that Socket Mode is on in the app's settings.`;
}
