import { isSlackApiEndpoint } from './slack-endpoint';

/**
 * The deployment variable holding the secret the Socket Mode bridge (`slack-socket/`, RM7)
 * presents to the backend's internal HTTP routes. Generated by the setup verb, written to the
 * deployment and to the bridge's environment alike; absent where no bridge runs, and then no
 * request carries buttons.
 */
export const SOCKET_BRIDGE_SECRET_VAR = 'DAY0_SOCKET_BRIDGE_SECRET';

/** Why an employee's decision requests carry no Approve and Reject buttons. */
export type ButtonsUnavailable =
  /** The card is not Slack's documented Web API (an MCP chat tool sends text alone). */
  | 'not-slack-api'
  /** The card connects through a token that is not an app Day0 created for the employee. */
  | 'no-own-app'
  /** The employee's app has no app-level token yet (a person generates it, K2). */
  | 'no-app-level-token'
  /** The deployment runs no Socket Mode bridge to carry a press. */
  | 'no-bridge'
  /**
   * The deployment holds the bridge's secret, but the bridge has reported no live connection for
   * the card's app lately (D-6 (b), W12-R16): it is stopped, cannot reach Slack, or predates the
   * report (0.17.0), so a press would reach nobody.
   */
  | 'bridge-down';

/** Whether an employee's decision requests carry Approve and Reject buttons, and why not. */
export type DecisionButtons =
  | { readonly available: true }
  | { readonly available: false; readonly why: Exclude<ButtonsUnavailable, 'no-bridge'> }
  | {
      readonly available: false;
      readonly why: 'no-bridge';
      /** Whether the app's app-level token is stored, so the bridge is all that is missing. */
      readonly tokenStored: boolean;
    };

/** The fields of a chat card the buttons depend on. */
export interface ButtonsCard {
  readonly path?: string;
  readonly endpoint?: string;
  readonly provisioning?: { readonly appLevelTokenCredentialId?: unknown };
}

/**
 * What a card knows of the Socket Mode bridge for its own app: `unconfigured` where the deployment
 * holds no bridge secret, `live` where the bridge reported a live connection for the card's app
 * within {@link SOCKET_HEARTBEAT_FRESH_MS}, and `down` otherwise (D-6 (b), W12-R16).
 */
export type SocketBridgeState = 'unconfigured' | 'down' | 'live';

/**
 * Whether a chat card's decision requests carry buttons (wave 12, 12-M; RM3 (a)): only on Slack's
 * documented Web API, through the employee's own app, on a deployment whose Socket Mode bridge is
 * configured, once the app's app-level token has landed, and while the bridge reports a live
 * connection for the app (D-6 (b)). The bridge's secret is read before the token, so a card on a
 * deployment that runs none asks for no token it could not use (W12-R18); its liveness after the
 * token, since the bridge dials only an app that has one. Otherwise the reason the card shows; the
 * typed code still decides where the app takes messages (W12V-7).
 *
 * @param card - The chat card the requests go through.
 * @param bridge - What the card knows of the bridge ({@link socketBridgeStateFor}).
 */
export function decisionButtonsFor(card: ButtonsCard, bridge: SocketBridgeState): DecisionButtons {
  if (card.path !== 'documented-api' || !isSlackApiEndpoint(card.endpoint)) {
    return { available: false, why: 'not-slack-api' };
  }
  if (card.provisioning === undefined) return { available: false, why: 'no-own-app' };
  const tokenStored = card.provisioning.appLevelTokenCredentialId !== undefined;
  if (bridge === 'unconfigured') return { available: false, why: 'no-bridge', tokenStored };
  if (!tokenStored) return { available: false, why: 'no-app-level-token' };
  if (bridge === 'down') return { available: false, why: 'bridge-down' };
  return { available: true };
}

/**
 * How old an unchanged report may grow before the backend writes it again: the bridge reports
 * every 30 seconds, and a row rewritten that often would wake every reader of it for nothing.
 */
export const SOCKET_HEARTBEAT_REFRESH_MS = 2 * 60_000;

/**
 * How recent a live report must be for a card to read the bridge as live: the refresh, the sync
 * that lands it (30 seconds) and one missed sync (30 seconds). A bridge that stops cleanly reports
 * every app down as it goes; one that dies unseen reads as down this long after its last report.
 */
export const SOCKET_HEARTBEAT_FRESH_MS = 3 * 60_000;

/** The longest failure a report stores, so a bridge cannot fill the row. */
const HEARTBEAT_FAILURE_LIMIT = 300;

/** A card's newest heartbeat as the readers see it (`socketHeartbeats`). */
export interface SocketHeartbeatReading {
  readonly appId: string;
  readonly live: boolean;
  readonly reportedAt: number;
}

/**
 * What a card knows of the bridge for its own app.
 *
 * @param configured - Whether the deployment holds the bridge's secret ({@link socketBridgeConfigured}).
 * @param report - The card's newest heartbeat, if the bridge ever reported on it.
 * @param appId - The card's own app, if it has one.
 * @param now - The clock, in epoch milliseconds.
 */
export function socketBridgeStateFor(
  configured: boolean,
  report: SocketHeartbeatReading | null | undefined,
  appId: string | undefined,
  now: number,
): SocketBridgeState {
  if (!configured) return 'unconfigured';
  const live =
    report !== null &&
    report !== undefined &&
    appId !== undefined &&
    report.appId === appId &&
    report.live &&
    now - report.reportedAt <= SOCKET_HEARTBEAT_FRESH_MS;
  return live ? 'live' : 'down';
}

/**
 * Whether one report is written over the card's row: its first, a change of liveness or app, or an
 * unchanged one once the row is {@link SOCKET_HEARTBEAT_REFRESH_MS} old.
 *
 * @param kept - The card's row, if any.
 * @param report - What the bridge reports now.
 * @param now - The clock, in epoch milliseconds.
 */
export function heartbeatWriteDue(
  kept: SocketHeartbeatReading | null,
  report: Pick<SocketHeartbeatReading, 'appId' | 'live'>,
  now: number,
): boolean {
  return (
    kept === null ||
    kept.live !== report.live ||
    kept.appId !== report.appId ||
    now - kept.reportedAt >= SOCKET_HEARTBEAT_REFRESH_MS
  );
}

/** One app in the bridge's report, as it posts it to `/slack-socket/heartbeat`. */
export interface SocketHeartbeatReport {
  /** The card the app carries presses for, as the apps list named it. */
  readonly surfaceId: string;
  readonly appId: string;
  /** Whether the bridge holds a greeted connection for the app. */
  readonly live: boolean;
  /** When the live connection was greeted. */
  readonly liveSince?: number;
  /** Why the bridge could not open the app's connection, the last time it could not. */
  readonly failure?: string;
}

/**
 * Read the bridge's report: the apps it holds, each by its card and app with whether it is live.
 * An entry missing one of those is dropped; a body with no list of apps is not a report.
 *
 * @param body - The request's JSON body.
 */
export function parseHeartbeat(body: unknown): SocketHeartbeatReport[] | undefined {
  const apps = record(body)?.apps;
  if (!Array.isArray(apps)) return undefined;
  return apps.flatMap((entry): SocketHeartbeatReport[] => {
    const app = record(entry);
    const surfaceId = text(app?.surfaceId);
    const appId = text(app?.appId);
    if (surfaceId === undefined || appId === undefined || typeof app?.live !== 'boolean') {
      return [];
    }
    const liveSince = typeof app.liveSince === 'number' ? app.liveSince : undefined;
    const failure = text(app.failure)?.slice(0, HEARTBEAT_FAILURE_LIMIT);
    return [
      {
        surfaceId,
        appId,
        live: app.live,
        ...(liveSince === undefined ? {} : { liveSince }),
        ...(failure === undefined ? {} : { failure }),
      },
    ];
  });
}

/**
 * Whether this deployment's environment holds the bridge's secret.
 *
 * @param env - The environment to read; the process's own by default.
 */
export function socketBridgeConfigured(
  env: Readonly<Record<string, string | undefined>> = process.env,
): boolean {
  return (env[SOCKET_BRIDGE_SECRET_VAR] ?? '').trim() !== '';
}

/** One button press, as the bridge forwards it from a Socket Mode `block_actions` envelope. */
export interface SocketPress {
  /** The Slack user who pressed. */
  readonly userId: string;
  readonly teamId?: string;
  /** The app whose message carried the button. */
  readonly appId: string;
  readonly channelId: string;
  /** The message the button is on. */
  readonly messageTs: string;
  /** When the press happened, Slack's own timestamp: the press's key, so a redelivery is one press. */
  readonly actionTs: string;
  readonly action: { readonly action_id: string; readonly value?: string };
}

function record(value: unknown): Record<string, unknown> | undefined {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : undefined;
}

function text(value: unknown): string | undefined {
  return typeof value === 'string' && value.trim() !== '' ? value : undefined;
}

/**
 * Read a Socket Mode envelope's payload as one button press, or nothing: only a `block_actions`
 * payload naming the user, the app, the message, its channel and an action with its timestamp.
 *
 * @param payload - The envelope's `payload`, as Slack sent it.
 */
export function parsePress(payload: unknown): SocketPress | undefined {
  const body = record(payload);
  if (body?.type !== 'block_actions') return undefined;
  const container = record(body.container);
  const first = Array.isArray(body.actions) ? record(body.actions[0]) : undefined;
  const userId = text(record(body.user)?.id);
  const appId = text(body.api_app_id);
  const channelId = text(container?.channel_id) ?? text(record(body.channel)?.id);
  const messageTs = text(container?.message_ts);
  const actionId = text(first?.action_id);
  const actionTs = text(first?.action_ts);
  if (!userId || !appId || !channelId || !messageTs || !actionId || !actionTs) return undefined;
  const teamId = text(record(body.team)?.id);
  const value = text(first?.value);
  return {
    userId,
    ...(teamId === undefined ? {} : { teamId }),
    appId,
    channelId,
    messageTs,
    actionTs,
    action: { action_id: actionId, ...(value === undefined ? {} : { value }) },
  };
}

async function digest(value: string): Promise<Uint8Array> {
  return new Uint8Array(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value)));
}

/**
 * Whether an `Authorization` header presents the bridge's secret as a bearer token. Both sides are
 * hashed before they are compared byte for byte without an early exit, so the time taken says
 * nothing about how much of the secret a guess got right. An empty secret matches nothing.
 *
 * @param header - The request's `Authorization` header, if any.
 * @param secret - The deployment's {@link SOCKET_BRIDGE_SECRET_VAR}.
 */
export async function bridgeSecretMatches(header: string | null, secret: string): Promise<boolean> {
  if (secret === '' || header === null || !header.startsWith('Bearer ')) return false;
  const [presented, expected] = await Promise.all([
    digest(header.slice('Bearer '.length)),
    digest(secret),
  ]);
  let difference = 0;
  for (let index = 0; index < expected.length; index += 1) {
    difference |= (presented[index] ?? 0) ^ (expected[index] ?? 0);
  }
  return difference === 0;
}

/** An app-level token's shape: Slack's `xapp-` prefix and its token characters. */
const APP_LEVEL_TOKEN = /^xapp-[A-Za-z0-9_-]{8,}$/;

/** Whether a pasted value has an app-level token's shape. */
export function isAppLevelTokenShape(value: string): boolean {
  return APP_LEVEL_TOKEN.test(value);
}

/** Why a pasted value was refused before Slack was asked: it is not an app-level token. */
export const NOT_AN_APP_LEVEL_TOKEN =
  "That is not an app-level token: Slack's app-level tokens start with xapp-. Generate one in the app's settings under Basic Information, App-Level Tokens, with the connections:write scope.";

/** Why a card takes no app-level token: it connects through no app of the employee's own. */
export const NO_OWN_APP_FOR_TOKEN =
  "This card has no Slack app of the employee's own, so it takes no app-level token. Create the employee's own Slack app on this card first; until then the request's typed code decides.";

/**
 * Why Slack refused an app-level token when Day0 opened a connection with it.
 *
 * @param appName - The employee's app, as the card names it.
 * @param reason - Slack's refusal, the token already removed.
 */
export function appLevelTokenRefused(appName: string, reason: string): string {
  return `Slack did not accept this app-level token (${reason}). Check that it was generated for ${appName} with the connections:write scope, and that Socket Mode is on in the app's settings.`;
}
