/**
 * Generate the root `NOTICE` (decision N18) and check that the tracked one is current.
 *
 *   pnpm exec tsx scripts/notice.ts           write NOTICE
 *   pnpm exec tsx scripts/notice.ts --check   exit 1 when NOTICE is stale
 *
 * The file is built from four sources, so it cannot drift from the tree: the
 * direct dependencies in `package.json` with the licence and holder their
 * installed package states; the production graph under `node_modules`, for
 * the transitive packages whose licence carries a notice duty; `pnpm-lock.yaml`
 * for the sharp libvips binaries, which install per platform; the compose file
 * and the model catalogue for the pinned service version and the model names;
 * and the tables below for what no package manifest describes (the images the
 * compose file runs, the model credits, the avatar art, the adapted files).
 * Every version and name that can move lives in one of those sources, never in
 * this script, so a bump the gate does not see cannot leave NOTICE wrong. The
 * licence texts the
 * LGPL and MPL require travel with it from `licenses/`. The gate runs the
 * check (`tests/scripts/notice.test.ts`).
 */
import { existsSync, readdirSync, readFileSync, realpathSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';
import { CURATED_MODELS } from './models';

/** One package as its installed manifest and licence file describe it. */
export interface PackageLicence {
  readonly name: string;
  readonly version: string;
  readonly licence: string;
  readonly holder: string;
  /** Whether the package ships a licence file of its own. */
  readonly licenceFile: boolean;
}

/** A transitive package whose licence or NOTICE file asks something of a redistributor. */
export interface TransitiveNotice extends PackageLicence {
  /** The package's own NOTICE file, verbatim, when it ships one. */
  readonly notice?: string;
}

/** The versions and names NOTICE credits that the compose file, the lockfile or the model catalogue pin. */
export interface NoticePins {
  /** The `@notionhq/notion-mcp-server` version the docs-notion service runs. */
  readonly notionMcpServer: string;
  /** The redactor's default span model, as the compose file names it. */
  readonly redactorModel: string;
  /** The local model route's default, the first model the catalogue recommends. */
  readonly localModel: string;
  /** The sharp-libvips release the lockfile resolves. */
  readonly libvipsRelease: string;
}

/** Everything the NOTICE is rendered from. */
export interface NoticeInput {
  readonly runtime: readonly PackageLicence[];
  readonly development: readonly PackageLicence[];
  readonly transitive: readonly TransitiveNotice[];
  /** The sharp prebuilds carrying libvips that the lockfile resolves, as `name@version`. */
  readonly libvips: readonly string[];
  readonly pins: NoticePins;
  /** Tracked source files whose header says they were lifted from Protean. */
  readonly proteanFiles: readonly string[];
  /** The licence texts under `licenses/`, by file name. */
  readonly texts: Readonly<Record<string, string>>;
}

/** Licences that ask a redistributor for nothing beyond the licence line this file already gives. */
const PLAIN_LICENCES: ReadonlySet<string> = new Set([
  'MIT',
  'ISC',
  'Apache-2.0',
  'BSD-2-Clause',
  'BSD-3-Clause',
  '0BSD',
  'Unlicense',
  '(Apache-2.0 AND BSD-3-Clause)',
]);

/**
 * The prebuilds that carry libvips install per platform, so they come from the
 * lockfile, never the graph: the `sharp-libvips-*` packages, and the win32 and
 * wasm32 builds of sharp itself, which bundle libvips in their own package.
 */
const LIBVIPS = /^@img\/sharp-(?:libvips-|win32-|wasm32@)/;

/** The separate libvips packages, whose version is the sharp-libvips release. */
const LIBVIPS_RELEASE = /^@img\/sharp-libvips-[^@]+@(.+)$/;

/** The Notion MCP server the docs-notion service installs at start, pinned in its command. */
const NOTION_MCP_PIN = /@notionhq\/notion-mcp-server@([\w.-]+)/;

/** The redactor's default model, as the compose file's `REDACTOR_MODEL` fallback names it. */
const REDACTOR_MODEL_PIN = /REDACTOR_MODEL=\$\{REDACTOR_MODEL:-([^}]+)\}/;

/** The licence texts `licenses/` carries, in the order NOTICE appends them. */
export const LICENCE_TEXTS = ['LGPL-3.0.txt', 'GPL-3.0.txt', 'MPL-2.0.txt'] as const;

const HEADER = `Day0
Copyright 2026 Brian Isaac

Day0 is licensed under the Apache License, Version 2.0 (see LICENSE). This
file lists the third-party works it adapts, runs, downloads or depends on,
with the licence and the holder each states, and carries the notices and
licence texts those licences require of a redistributor.

This file is generated by scripts/notice.ts from package.json, the installed
dependency graph, pnpm-lock.yaml and the tables in that script. Do not edit it
by hand: run \`pnpm exec tsx scripts/notice.ts\` and commit the result. The
gate fails when it is stale.`;

const ADAPTED = `docker-compose.yml is adapted from the reference compose file of the
Convex self-hosted backend (https://github.com/get-convex/convex-backend),
Functional Source License, Version 1.1, ALv2 Future License
(FSL-1.1-ALv2), Copyright 2026 Convex, Inc.`;

/** The images the compose file runs, with the Notion server at the version it pins. */
function servicesBody(pins: NoticePins): string {
  return `The compose file pulls these images by digest; the repository does not
contain or redistribute them.

- Convex backend and dashboard (ghcr.io/get-convex/convex-backend,
  ghcr.io/get-convex/convex-dashboard): FSL-1.1-ALv2, Copyright 2026
  Convex, Inc. The licence permits any use that does not compete with
  Convex; each release converts to Apache-2.0 on the second anniversary of
  its publication. Day0 is an application on the backend, not a substitute
  for it (decision A15). SQLite is the supported store.
- Ollama (ollama/ollama), the bundled local model service: MIT,
  Copyright (c) Ollama.
- Playwright MCP (mcr.microsoft.com/playwright/mcp), the browser component:
  Apache-2.0, Copyright (c) Microsoft Corporation.
- Notion MCP server (@notionhq/notion-mcp-server ${pins.notionMcpServer}, installed by the
  docs-notion-mcp service at start): MIT, Copyright (c) 2025 Notion Labs, Inc.
- python:3.12-slim (the sandbox and the redactor): Python is under the
  Python Software Foundation License Version 2 (PSF-2.0); the image's other
  software is under its own licences.
- node:22-alpine (the Notion component and the two test doubles): Node.js is
  MIT, Copyright Node.js contributors; the image's other software is under its
  own licences.`;
}

/** The redactor models this script can credit, by the id the compose file names. */
const REDACTOR_MODEL_CREDITS: Readonly<Record<string, string>> = {
  'urchade/gliner_multi_pii-v1': `- urchade/gliner_multi_pii-v1, the redactor's span model: Apache-2.0,
  published on Hugging Face by the account urchade. GLiNER is described in
  Urchade Zaratiana, Nadi Tomeh, Pierre Holat and Thierry Charnois, "GLiNER:
  Generalist Model for Named Entity Recognition using Bidirectional
  Transformer", Proceedings of NAACL-HLT 2024, pages 5364-5376.
- microsoft/mdeberta-v3-base, the span model's backbone, whose configuration
  and tokeniser the redactor loads: MIT, Copyright (c) Microsoft Corporation.`,
};

/** The local model families this script can credit, by the prefix of the id `ollama pull` takes. */
const LOCAL_MODEL_CREDITS: readonly { readonly prefix: string; readonly credit: string }[] = [
  {
    prefix: 'qwen3:',
    credit:
      "Qwen3 ({id} through Ollama, the local model route's default): Apache-2.0,\n  Copyright 2024 Alibaba Cloud.",
  },
];

/**
 * The models section, crediting the models the compose file and the catalogue name.
 *
 * @throws Error when either names a model this script has no credit for, so a
 *   model change fails the gate until its credit is written here.
 */
function modelsBody(pins: NoticePins): string {
  const redactor = REDACTOR_MODEL_CREDITS[pins.redactorModel];
  if (redactor === undefined) {
    throw new Error(
      `no NOTICE credit for the redactor model ${pins.redactorModel}: add it to scripts/notice.ts`,
    );
  }
  const local = LOCAL_MODEL_CREDITS.find(({ prefix }) => pins.localModel.startsWith(prefix));
  if (local === undefined) {
    throw new Error(
      `no NOTICE credit for the local model ${pins.localModel}: add it to scripts/notice.ts`,
    );
  }
  return `Model weights are downloaded at first use, pinned by digest where the
component verifies them, and never stored in this repository.

${redactor}
- ${local.credit.replace('{id}', pins.localModel)}

Hosted models reached over an API are the operator's choice and account; none
is distributed.`;
}

const IMAGES = `The pixel-art agent faces under public/agent-avatars/faces/ come from the
public Singapore Codex Pets community gallery
(https://singapore-pet-share.vercel.app/), which is built on the
portons/codex-pet-share template (MIT, Copyright (c) 2026 Codex Pet Share
contributors). The gallery states no licence for its images. They are used as
demo art with this credit, the product names no person they depict, and they
are not covered by this repository's Apache-2.0 licence.`;

/** What the libvips binaries bundle, as the named sharp-libvips release's THIRD-PARTY-NOTICES.md lists it. */
function libvipsNote(release: string): string {
  return `LGPL-3.0-or-later. These are optional dependencies of next through sharp
(Next.js's image pipeline). No day0 code calls sharp or next/image and this
repository ships no build containing them; the terms below bind whoever
distributes a build that does. The libvips binaries bundle these components
(sharp-libvips ${release}, THIRD-PARTY-NOTICES.md):

  LGPL-3.0: fribidi, glib, libexif, libheif, librsvg, libvips, pango,
    proxy-libintl (used under the "any later version" clause of LGPLv2 or
    LGPLv2.1)
  MPL-2.0: cairo
  BSD-2-Clause and the Alliance for Open Media Patent License 1.0: aom
  MIT: cgif, expat, harfbuzz, lcms, libffi, libnsgif, libxml2, pixman
  BSD-2-Clause: libarchive, libimagequant
  Apache-2.0 and BSD-3-Clause: highway
  New BSD: libwebp
  zlib, IJG and BSD-3-Clause: mozjpeg
  zlib: zlib-ng
  libpng: libpng; BSD-2-Clause and libpng: libspng
  BSD-like: fontconfig, freetype, libtiff

The LGPL-3.0 and the GPL-3.0 it supplements, and the MPL-2.0, are appended at
the end of this file.`;
}

const VERCEL_OG = `@vercel/og, compiled into next under next/dist/compiled/@vercel/og:
MPL-2.0 (appended at the end of this file). Day0 does not call it.`;

/** The opening of the MIT licence's grant, for a package whose manifest names no licence. */
const MIT_GRANT = /Permission is hereby granted, free of charge, to any person obtaining a copy/;

/**
 * The licence a manifest declares, as one string: the `license` field, the
 * legacy `licenses` list, or the MIT grant in the licence file itself.
 */
function packageLicence(
  manifest: Record<string, unknown>,
  licenceText: string | undefined,
): string {
  const licence = manifest.license;
  if (typeof licence === 'string') return licence;
  if (licence && typeof licence === 'object' && 'type' in licence) return String(licence.type);
  const legacy = manifest.licenses;
  if (Array.isArray(legacy) && legacy.length > 0) {
    const types = legacy.map((entry: unknown) =>
      entry && typeof entry === 'object' && 'type' in entry ? String(entry.type) : String(entry),
    );
    return types.length === 1 ? types[0]! : `(${types.join(' OR ')})`;
  }
  if (licenceText !== undefined && MIT_GRANT.test(licenceText)) return 'MIT';
  return 'not stated';
}

/** The author a manifest names, without an address. */
function manifestAuthor(manifest: Record<string, unknown>): string | undefined {
  const author = manifest.author;
  const name =
    typeof author === 'string'
      ? author
      : author && typeof author === 'object' && 'name' in author
        ? String(author.name)
        : undefined;
  return name?.replace(/\s*[<(].*$/, '').trim() || undefined;
}

/**
 * The first copyright line of a licence file, skipping the Apache template's
 * placeholder and the licence body's own use of the word.
 */
export function copyrightLine(licenceText: string): string | undefined {
  return licenceText
    .split(/\r?\n/)
    .map((line) => line.trim())
    .find((line) => /^Copyright\s/.test(line) && !/\[yyyy\]|\[name of|Copyright notice/i.test(line))
    ?.replace(/\s+/g, ' ');
}

/**
 * The first file in a directory, by name, that a pattern matches. The listing
 * is sorted because `readdirSync` returns the file system's order, which
 * differs between machines when a package ships two matching files.
 */
function firstFileMatching(directory: string, pattern: RegExp): string | undefined {
  return readdirSync(directory)
    .filter((file) => pattern.test(file))
    .sort()[0];
}

/** A package directory's licence file, if it ships one. */
function licenceFileOf(directory: string): string | undefined {
  return firstFileMatching(directory, /^(?:licen[cs]e|copying)(?:\.|$)/i);
}

/** Read one installed package's licence facts from its directory. */
export function readPackage(directory: string): PackageLicence {
  const manifest = JSON.parse(readFileSync(join(directory, 'package.json'), 'utf8')) as Record<
    string,
    unknown
  >;
  const file = licenceFileOf(directory);
  const text = file ? readFileSync(join(directory, file), 'utf8') : undefined;
  const line = text === undefined ? undefined : copyrightLine(text);
  return {
    name: String(manifest.name),
    version: String(manifest.version),
    licence: packageLicence(manifest, text),
    holder: line ?? manifestAuthor(manifest) ?? 'holder not stated by the package',
    licenceFile: file !== undefined,
  };
}

/** The `node_modules` directory a package's own dependencies resolve from under pnpm. */
function siblingModules(realDirectory: string, name: string): string {
  return name.split('/').reduce((directory) => dirname(directory), realDirectory);
}

/**
 * The production graph: every package reachable from `package.json`'s
 * dependencies through dependencies, optional and peer dependencies that are
 * installed.
 *
 * @returns Real package directories, keyed and ordered by `name@version`.
 */
export function productionGraph(root: string): Map<string, string> {
  const manifest = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')) as {
    dependencies?: Record<string, string>;
  };
  const found = new Map<string, string>();
  const seen = new Set<string>();
  const queue = Object.keys(manifest.dependencies ?? {}).map((name) =>
    join(root, 'node_modules', name),
  );
  while (queue.length > 0) {
    const candidate = queue.shift()!;
    if (!existsSync(join(candidate, 'package.json'))) continue;
    const real = realpathSync(candidate);
    if (seen.has(real)) continue;
    seen.add(real);
    const own = JSON.parse(readFileSync(join(real, 'package.json'), 'utf8')) as {
      name: string;
      version: string;
      dependencies?: Record<string, string>;
      optionalDependencies?: Record<string, string>;
      peerDependencies?: Record<string, string>;
    };
    found.set(`${own.name}@${own.version}`, real);
    const modules = siblingModules(real, own.name);
    for (const name of new Set([
      ...Object.keys(own.dependencies ?? {}),
      ...Object.keys(own.optionalDependencies ?? {}),
      ...Object.keys(own.peerDependencies ?? {}),
    ])) {
      queue.push(join(modules, name));
    }
  }
  return new Map([...found.entries()].sort(([a], [b]) => a.localeCompare(b, 'en')));
}

/** A package's own NOTICE file, if it ships one. */
function noticeFileOf(directory: string): string | undefined {
  const file = firstFileMatching(directory, /^notice(?:\.|$)/i);
  return file ? readFileSync(join(directory, file), 'utf8').trim() : undefined;
}

/**
 * The transitive production packages that carry a notice duty: a licence
 * other than the plain permissive ones, or a NOTICE file of their own. The
 * libvips binaries are left to the lockfile, since which of them install
 * depends on the machine.
 */
export function transitiveNotices(graph: ReadonlyMap<string, string>): TransitiveNotice[] {
  const notices: TransitiveNotice[] = [];
  for (const directory of graph.values()) {
    const found = readPackage(directory);
    if (LIBVIPS.test(found.name)) continue;
    const notice = noticeFileOf(directory);
    if (PLAIN_LICENCES.has(found.licence) && notice === undefined) continue;
    notices.push(notice === undefined ? found : { ...found, notice });
  }
  return notices;
}

/** The sharp prebuilds carrying libvips that the lockfile resolves, for every platform. */
export function lockedLibvips(lockfile: string): string[] {
  const packages = (parse(lockfile) as { packages?: Record<string, unknown> }).packages ?? {};
  return Object.keys(packages)
    .filter((key) => LIBVIPS.test(key))
    .sort();
}

/**
 * The one sharp-libvips release the lockfile's libvips packages resolve to.
 *
 * @throws Error when the lockfile resolves none, or more than one release,
 *   since NOTICE lists one release's bundled components.
 */
export function libvipsRelease(prebuilds: readonly string[]): string {
  const releases = [...new Set(prebuilds.flatMap((name) => LIBVIPS_RELEASE.exec(name)?.[1] ?? []))];
  if (releases.length !== 1) {
    throw new Error(
      `expected one sharp-libvips release in pnpm-lock.yaml, found ${releases.length === 0 ? 'none' : releases.join(', ')}`,
    );
  }
  return releases[0]!;
}

/**
 * The pinned versions and names the compose file states.
 *
 * @throws Error when the compose file no longer pins the Notion server or
 *   names the redactor's default model in the shape this reads.
 */
export function composePins(
  compose: string,
): Pick<NoticePins, 'notionMcpServer' | 'redactorModel'> {
  const notionMcpServer = NOTION_MCP_PIN.exec(compose)?.[1];
  const redactorModel = REDACTOR_MODEL_PIN.exec(compose)?.[1];
  if (notionMcpServer === undefined || redactorModel === undefined) {
    throw new Error(
      'docker-compose.yml no longer pins @notionhq/notion-mcp-server@<version> or names REDACTOR_MODEL=${REDACTOR_MODEL:-<model>}',
    );
  }
  return { notionMcpServer, redactorModel };
}

/** Tracked source files that say they were lifted from, or follow, Protean's. */
export function proteanFiles(root: string): string[] {
  const files: string[] = [];
  for (const top of ['app', 'convex', 'src']) {
    for (const entry of readdirSync(join(root, top), { recursive: true, withFileTypes: true })) {
      if (!entry.isFile() || !/\.tsx?$/.test(entry.name)) continue;
      const path = join(entry.parentPath, entry.name);
      if (/Lifted from Protean|\bProtean's\b/.test(readFileSync(path, 'utf8'))) {
        files.push(relative(root, path).split(sep).join('/'));
      }
    }
  }
  return files.sort();
}

/** Gather every input the NOTICE is rendered from. */
export function collectNoticeInput(root: string): NoticeInput {
  const manifest = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')) as {
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
  };
  const direct = (names: Record<string, string> | undefined): PackageLicence[] =>
    Object.keys(names ?? {})
      .sort()
      .map((name) => readPackage(realpathSync(join(root, 'node_modules', name))));
  const runtimeNames = new Set(Object.keys(manifest.dependencies ?? {}));
  const libvips = lockedLibvips(readFileSync(join(root, 'pnpm-lock.yaml'), 'utf8'));
  return {
    runtime: direct(manifest.dependencies),
    development: direct(manifest.devDependencies),
    transitive: transitiveNotices(productionGraph(root)).filter(
      (found) => !runtimeNames.has(found.name),
    ),
    libvips,
    pins: {
      ...composePins(readFileSync(join(root, 'docker-compose.yml'), 'utf8')),
      localModel: CURATED_MODELS[0]!.id,
      libvipsRelease: libvipsRelease(libvips),
    },
    proteanFiles: proteanFiles(root),
    texts: Object.fromEntries(
      LICENCE_TEXTS.map((name) => [name, readFileSync(join(root, 'licenses', name), 'utf8')]),
    ),
  };
}

/** One package as a NOTICE line. */
function packageLine(found: PackageLicence): string {
  const shipped = found.licenceFile ? '' : ' (no licence file in the package; from its manifest)';
  return `- ${found.name} ${found.version}: ${found.licence}, ${found.holder}${shipped}`;
}

/** A numbered section with a rule under its title. */
function section(number: number, title: string, body: string): string {
  const heading = `${number}. ${title}`;
  return `${heading}\n${'-'.repeat(heading.length)}\n\n${body}`;
}

/** The transitive section: grouped by the duty each licence carries. */
function transitiveBody(input: NoticeInput): string {
  const byLicence = (licence: string): TransitiveNotice[] =>
    input.transitive.filter((found) => found.licence === licence);
  const known = new Set(['BlueOak-1.0.0', 'CC-BY-4.0']);
  const blueOak = byLicence('BlueOak-1.0.0');
  const ccBy = byLicence('CC-BY-4.0');
  const withNotice = input.transitive.filter((found) => found.notice !== undefined);
  const other = input.transitive.filter(
    (found) => !known.has(found.licence) && found.notice === undefined,
  );
  const parts: string[] = [];
  if (blueOak.length > 0) {
    parts.push(
      'Blue Oak Model License 1.0.0 (https://blueoakcouncil.org/license/1.0.0):\n\n' +
        blueOak.map(packageLine).join('\n'),
    );
  }
  if (ccBy.length > 0) {
    parts.push(
      'Creative Commons Attribution 4.0\n(https://creativecommons.org/licenses/by/4.0/); the browser support\n' +
        'data is from the Can I Use project (https://caniuse.com):\n\n' +
        ccBy.map(packageLine).join('\n'),
    );
  }
  for (const found of withNotice) {
    parts.push(
      `${packageLine(found)}\n\nIts NOTICE, reproduced as the licence requires:\n\n${indent(found.notice!)}`,
    );
  }
  if (other.length > 0) {
    parts.push(
      'Other licences (where a package offers a choice, Day0 takes BSD-3-Clause):\n\n' +
        other.map(packageLine).join('\n'),
    );
  }
  parts.push(
    "sharp's prebuilt libvips, for every platform pnpm-lock.yaml resolves:\n\n" +
      `${input.libvips.map((name) => `- ${name}`).join('\n')}\n\n${libvipsNote(input.pins.libvipsRelease)}`,
  );
  parts.push(VERCEL_OG);
  return parts.join('\n\n');
}

/** Indent every line of a block by four spaces. */
function indent(text: string): string {
  return text
    .split('\n')
    .map((line) => (line.trim() === '' ? '' : `    ${line}`))
    .join('\n');
}

/** Render the NOTICE text from its inputs. */
export function renderNotice(input: NoticeInput): string {
  const adapted =
    `${ADAPTED}\n\nThese files say in their header that they were lifted from, or follow,\n` +
    `Protean, the maintainer's own earlier codebase, under the same holder\nand licence:\n\n` +
    input.proteanFiles.map((file) => `- ${file}`).join('\n');
  const sections = [
    section(1, 'Works this repository adapts', adapted),
    section(2, 'Images the compose file runs', servicesBody(input.pins)),
    section(3, 'Models', modelsBody(input.pins)),
    section(4, 'Images in this repository', IMAGES),
    section(5, 'Direct dependencies', input.runtime.map(packageLine).join('\n')),
    section(
      6,
      'Development dependencies (used to build and test, not distributed)',
      input.development.map(packageLine).join('\n'),
    ),
    section(7, 'Transitive dependencies with notice duties', transitiveBody(input)),
    ...LICENCE_TEXTS.map((name, index) =>
      section(
        8 + index,
        `Licence text: ${name.replace(/\.txt$/, '')}`,
        input.texts[name]!.trimEnd(),
      ),
    ),
  ];
  return `${HEADER}\n\n\n${sections.join('\n\n\n')}\n`;
}

/** Write NOTICE, or with `--check` report whether it is current. */
function main(argv: readonly string[]): number {
  const root = join(dirname(fileURLToPath(import.meta.url)), '..');
  const rendered = renderNotice(collectNoticeInput(root));
  const path = join(root, 'NOTICE');
  if (argv.includes('--check')) {
    const current = existsSync(path) ? readFileSync(path, 'utf8') : '';
    if (current === rendered) return 0;
    console.error('NOTICE is stale: run `pnpm exec tsx scripts/notice.ts` and commit the result.');
    return 1;
  }
  writeFileSync(path, rendered);
  console.log(`wrote ${relative(process.cwd(), path) || 'NOTICE'}`);
  return 0;
}

if (process.argv[1] && realpathSync(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exitCode = main(process.argv.slice(2));
}
